Harden the way how libsqlite symlink is created
Signed-off-by: Stanislaw Kubiak <stanislaw.kubiak@nordsec.com>

diff --git a/contrib/scriptlets/rpm/posttrans b/contrib/scriptlets/rpm/posttrans
--- a/contrib/scriptlets/rpm/posttrans
+++ b/contrib/scriptlets/rpm/posttrans
@@ -18,10 +18,23 @@ export DBUS_SESSION_BUS_ADDRESS="unix:path=${XDG_RUNTIME_DIR}/bus"
 ldconfig
 
 # move the symlink file creation later, otherwise the update scripts will delete it
-set -e
-sqlite=$(ldconfig -p 2>/dev/null | grep 'libsqlite3.so.0' | sed -n 's/.*=>[[:space:]]*//p' | head -n1)
-ln -sf "${sqlite}" /usr/lib/nordvpn/libsqlite3.so
-set +e
+#
+# Iterate over all of the results, so symlink is not created pointing to an actual .so file
+# which might cause issues upon library bump.
+#
+sqlite=""
+for path in $(ldconfig -p 2>/dev/null | grep 'libsqlite3.so.0' | sed -n 's/.*=>[[:space:]]*//p'); do
+    if [ -L "$path" ]; then
+        sqlite="$path"
+        break
+    fi
+done
+
+if [ -n "$sqlite" ]; then
+    ln -sf "$sqlite" "${LIBS_DIR}/libsqlite3.so"
+else
+    echo "WARNING: no symlink to libsqlite3.so.0 found in ldconfig cache; nordvpnd may fail to start" >&2
+fi
 # ldconfig needs to be executed twice in case libsqlite3.so.0 was not available during a lookup
 ldconfig
 
