Add keeping of killswitch rules when upgrading

diff --git a/contrib/scriptlets/rpm/preun b/contrib/scriptlets/rpm/preun
--- a/contrib/scriptlets/rpm/preun
+++ b/contrib/scriptlets/rpm/preun
@@ -3,7 +3,7 @@
 ENV=$(ps --no-headers -o comm 1)
 
 case "$1" in
-    0|1)
+    0)
         case "$ENV" in
             init)
                 /etc/init.d/nordvpn stop &>/dev/null || :
@@ -21,6 +21,27 @@ case "$1" in
             *)
                 echo "[ERROR] Unknown environment \`$ENV'"
             ;;
+        esac
+    ;;
+    1)
+        case "$ENV" in
+        init)
+            /etc/init.d/nordvpn upgrade-stop &>/dev/null || :
+            update-rc.d -f nordvpn remove &>/dev/null || :
+        ;;
+        systemd)
+            sudo systemctl set-property nordvpnd.service Restart=no &>/dev/null || :
+            sudo systemctl kill --signal=SIGUSR1 nordvpnd.service &>/dev/null || :
+            sudo systemctl stop nordvpnd.socket &>/dev/null || :
+            sudo systemctl disable nordvpnd.service &>/dev/null || :
+            sudo systemctl disable nordvpnd.socket &>/dev/null || :
+            sudo systemctl daemon-reload &>/dev/null || :
+        ;;
+        *sh) # executed in docker
+        ;;
+        *)
+            echo "[ERROR] Unknown environment \`$ENV'"
+        ;;
         esac
     ;;
 esac
